### ISSUE TITLE
Heavy dependencies for "Base" package lead to long compile times

### ISSUE THREAD

**Issue by evetion** [JuliaEarth/GeoStats.jl#124]
Over at evetion/GeoArrays.jl, which uses this package, I'm hitting long compile times (1min 43s), of which `GeoStatsBase` takes at least a minute.

I would assume this is a base package, to include the correct signatures, and the heavy lifting to be done in other packages. Would this assumption be correct and are the many dependencies necessary? Not sure if this is fixable, otherwise it's just for awareness.

You can check the compile order/tree/times with this [experimental PR](https://github.com/JuliaLang/julia/pull/37374):
![compile](https://user-images.githubusercontent.com/8655030/94992922-ddc9b700-057c-11eb-9537-cd8057d8e164.gif)

**Comment by evetion** [comment]
That would be a BaseBase package, very meta :metal:. I understand you don't want a thousand different implementation packages (anymore). Not sure what the correct name would be. GeoStatsCommon? GeoStatsInterface? Or try to move out all the implementation stuff, but I don't have the overview to tell what should be in Base and what not.

What I'm using is very short and all in here: https://github.com/evetion/GeoArrays.jl/blob/master/src/interpolate.jl#L1. Only the type `AbstractSolver`, and the `georef`, `solve`, `RegularGrid`, `EstimationProblem` and `CopyMapper` functions.

**Comment by juliohm** [comment]
We could either migrate the implementations to some GeoStatsUtils.jl package or migrate the interface to some GeoStatsInterface.jl package. I agree with you we need to refactor this in order to avoid long compile times in downstream packages. I wish package precompilation was a thing already :sob: Looking forward to next releases of the language.

**Comment by juliohm** [comment]
@evetion so based on your use case, I think we can improve the current situation in a couple steps.

- First, we need to double check that we still need `CopyMapper`. @exepulveda recently fixed an issue in the Kriging solver, which may free us from using the CopyMapper explicitly.
- Second, we need to migrate the implementations to a new package, I am thinking about GeoStatsLib.jl as the name.
- Third, we will still need to move `RegularGrid` somewhere else. I am waiting for people in GeometryBasics.jl to confirm if they are interested in merging [my fixes](https://github.com/JuliaGeometry/GeometryBasics.jl/pull/93) moving forward or if we should fork our own repository for spatial domains and meshes.

If you would like to speed up the resolution of this issue, perhaps you could comment on that PR about the refactoring of GeometryBasics.jl.

**Comment by juliohm** [comment]
Update on this:

- `CopyMapper` has been refactored and it is probably not needed anymore in the user side.
- `RegularGrid` will now live in Meshes.jl under the name `CartesianGrid` like all other domain types.

In Julia v1.6-beta1 this compilation time is much improved due to the new parallel features of the package manager. I think it is taking a couple of seconds now to build the entire stack. Let's see how things go.

**Comment by juliohm** [comment]
@evetion do you feel we still need to work on this to reduce the compilation times further? In Julia v1.6 things are much better now with Pkg parallel precompilation.

**Comment by juliohm** [comment]
Closing the issue assuming it is ok.
