### ISSUE TITLE
Memory allocation for nested variograms

### ISSUE THREAD

**Issue by hameye** [JuliaEarth/GeoStats.jl#172]
Iterator in nested variograms formula (distance, sill and nugget) might allocate more memory than expected :
```julia
julia> g = GaussianVariogram() + ExponentialVariogram() + SphericalVariogram()
NestedVariogram{3}
  structures
    └─GaussianVariogram(range=1.0, sill=1.0, nugget=0.0)
    └─ExponentialVariogram(range=1.0, sill=1.0, nugget=0.0)
    └─SphericalVariogram(range=1.0, sill=1.0, nugget=0.0)
  coefficients
    └─2
    └─1
    └─1

julia> @allocated sum(c*sill(γ) for (c, γ) in zip(g.cs, g.γs))
6153557

julia> @allocated sill(g)
784
```

Might this be causing kriging to be slow compared to simple variogram model ?

**Comment by juliohm** [comment]
Thanks for reporting the issue @hameye. We need to figure out what is happening with the expressions that is causing unnecessary memory allocation. We can ask on Zulip to see if people can help more quickly.

**Comment by juliohm** [comment]
We have addressed most memory allocation issues on the latest release. There is still one missing item that would bring this allocation to zero in theory. @hameye would you be willing to submit a PR to Variography.jl with the following experiment?

Instead of:

```julia
sill(g::NestedVariogram) = raw(sum(c*sill(γ) for (c, γ) in zip(g.cs, g.γs)))
```

we could try:

```julia
sill(g::NestedVariogram) =  raw(sum(g.cs .* map(sill, g.γs)))
```

The call to `zip` seems to allocate memory due to the tuples created on the fly. If you can help benchmarking this change with `@btime sill(g)` that would be super helpful. A similar change should be made to the following methods:

```julia
(g::NestedVariogram)(h) = raw(sum(c*γ(h) for (c, γ) in zip(g.cs, g.γs)))
(g::NestedVariogram)(x::Point, y::Point) = raw(sum(c*γ(x, y) for (c, γ) in zip(g.cs, g.γs)))
```

Please let me know if you would like to spend some time helping with this. We should have zero allocations in theory after these changes are implemented. I am happy to help with reviewing the PR.

**Comment by hameye** [comment]
Former implementation 
```julia
julia> γ = NuggetEffect(0.2) + GaussianVariogram(nugget=0.1, sill=0.6, range=50.0) + GaussianVariogram(sill=0.2, range=150.0)
NestedVariogram{3}
  structures
    └─NuggetEffect(range=0.0, sill=0.2, nugget=0.2)
    └─GaussianVariogram(range=50.0, sill=0.6, nugget=0.1)
    └─GaussianVariogram(range=150.0, sill=0.2, nugget=0.0)
  coefficients
    └─1
    └─1
    └─1

julia> @btime sill(γ)
  431.242 ns (16 allocations: 832 bytes)
1.0

julia> @btime nugget(γ)
  445.766 ns (16 allocations: 832 bytes)
0.30000000000000004

julia> x = Point([0,0,0])
Point(0, 0, 0)

julia> y = Point([4.,4.,4.])
Point(4.0, 4.0, 4.0)

julia> @btime γ(x,y)
  522.948 ns (20 allocations: 992 bytes)
0.32926410891317165

julia> @btime γ(5)
  452.426 ns (16 allocations: 832 bytes)
0.3154447571325909
```
New implementation
```julia
julia> @btime sill(γ)
  16.329 ns (1 allocation: 16 bytes)
1.0

julia> @btime nugget(γ)
  14.973 ns (1 allocation: 16 bytes)
0.30000000000000004

julia> @btime γ(x,y)
  76.959 ns (1 allocation: 16 bytes)
0.32926410891317165

julia> @btime γ(5)
  30.128 ns (1 allocation: 16 bytes)
0.3154447571325909

```
