### ISSUE TITLE
Change default heuristic for declustering to mode

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#177]
Currently the default block size in declustereted statistics is the median pairwise distance of a couple of samples. We could change the default to the mode instead.

**Comment by nshea3** [comment]
Hi @juliohm! I'd like to give this issue a try. I'm putting together a PR now, but I had a few questions I hoped you could help with before I make the PR. 

I'm testing my work against the [DeclusteredStatistics.jl](https://github.com/JuliaEarth/GeoStatsTutorials/blob/master/notebooks/DeclusteredStatistics.jl) notebook and I'm finding that the mode heuristic is not giving very good block sizes, resulting in a declustered mean that is even further from the true mean than the non-declustered mean. I'm wondering if this has to do with the fact that these distances are floats, so the mode is not necessarily the "highest density" because the high precision means two floats rarely match. 

https://github.com/JuliaEarth/GeoStatsBase.jl/blob/430333c0b131d3776590576c583e0624fd8bcb39/src/statistics/data.jl#L53-L68

Thanks! 
Nick

**Comment by juliohm** [comment]
Hi @nshea3 , that would be great, thank you for the help. In order to use the mode we need some binning of the interval or some form of convolution to transform the impulses of distance into something smooth where we can read the mode. If you can share some results, we can investigate it further.

**Comment by juliohm** [comment]
@nshea3 do you need any help to get it started?

**Comment by nshea3** [comment]
Hi! Still working on this - trying to figure out the best way to estimate the mode. 

I have a working example that finds the minimum distance between successive samples (steepest part of empirical CDF) and uses the midpoint as an estimate of the mode. I could put together a PR and discuss the changes there if that sounds like a reasonable approach. 

I found many more possible approaches in these stackoverflow posts:

- https://stats.stackexchange.com/questions/176112/how-to-find-the-mode-of-a-probability-density-function
- https://stats.stackexchange.com/questions/9666/identifying-modes-in-floating-point-data

I could use some help if you are leaning towards the convolution transformation approach as I am not familiar with that method.

**Comment by juliohm** [comment]
Hi Nicholas the recursive approach described in the first SO post seems
good. I'd just start with the PR and then we can align the minor technical
details.
