### ISSUE TITLE
Ordering problem in print methods

### ISSUE THREAD

**Issue by immaryw** [JuliaEarth/GeoStats.jl#181]
The order of variables looks messy. It may come from the [print method issue.](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/92e3ad70d5e24a0e1bed825faa9bd20baa4bde2b/src/ensembles.jl#L64)
```julia
grid = CartesianGrid(10,10)
vars = (:Z1=>Float64,:Z2=>Float64,:Z3=>Float64)
prob = SimulationProblem(grid, vars, 1)
solv = FFTGS(:Z1=>(mean=0., variogram=γ1), :Z2=>(mean=0., variogram=γ2),:Z3=>(mean=0., variogram=γ3))
sol = solve(prob, solv)
```
produce

```
2D Ensemble
  domain: 10×10 CartesianGrid{2,Float64}
  variables: Z2, Z3 and Z1
  N° reals:  1
```
The correct order should be Z1, Z2, Z3.

**Comment by juliohm** [comment]
Thank you @immaryw for reporting the issue. To fix it we need to do a few things:

1. Go in [this line](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/92e3ad70d5e24a0e1bed825faa9bd20baa4bde2b/src/solvers.jl#L66) before the loop and save the result of `covariables(problem, solver)` into a new variable
2. After the loop [here](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/92e3ad70d5e24a0e1bed825faa9bd20baa4bde2b/src/solvers.jl#L87) we need to use the saved variable to created a named tuple from the dictionary. This tuple should be returned instead of the dictionary.
3. Adapt the Ensemble struct according to have a named tuple of realizations instead of a dictionary [here](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/92e3ad70d5e24a0e1bed825faa9bd20baa4bde2b/src/ensembles.jl#L5-L66)

Let me know if you would like to tackle this issue, and I can help reviewing the PR. Otherwise I will try to find time after next week to fix it myself.

**Comment by juliohm** [comment]
Fixed in https://github.com/JuliaEarth/GeoStatsBase.jl/commit/4e12b760348cad3ff635d52dfc9d0b15231cf0cf
