### ISSUE TITLE
origin and spacing not taken into account when plotting

### ISSUE THREAD

**Issue by briochemc** [JuliaEarth/GeoStats.jl#61]
It seems that `origin` and `spacing` are not taken into account when plotting things onto grids.

(not-so-M)WE:

```julia
using Plots
origin = (-100.0, -200.0)
spacing = (5.0, 5.0)
X = origin[1]:100
Y = origin[2]:200
Z = [10sin(x/10) + y for x in X, y in Y]
plt1 = heatmap(X,Y,Z')
using GeoStats
Ω = RegularGridData{Float64}(OrderedDict(:Z=>Z))
RegularGridData(OrderedDict(:Z=>Z), origin .+ 1000, spacing)
plt2 = plot(Ω)
plot(plt1, plt2, layout=(2,1))
```

I was expecting the bottom plot to show the shifted origin and `(5.0,5.0)` spacing, but it does not?

<img width="1215" alt="Screen Shot 2020-06-03 at 10 16 18 am" src="https://user-images.githubusercontent.com/4486578/83581858-48dd8f80-a583-11ea-9fe4-065553f519b7.png">

**Comment by juliohm** [comment]
I recall this wasn't possible with Plots.jl + GR.jl recipes back then, but perhaps the recipe system got updated. I am not sure. Do you think you could try fix the plot recipe here? https://github.com/JuliaEarth/GeoStatsBase.jl/blob/master/src/plotrecipes/domains/regular_grid.jl#L5-L24

Instead of returning the 2D matrix, we could return:

```julia
X = coordinates(domain)
...
elseif N == 2
...
X[1,:], X[2,:], Z
```

The actual plan is to move from Plots.jl recipes to Makie.jl recipes in the next milestone.

**Comment by juliohm** [comment]
Fixed on master. Thanks for catching it :100:
